language: node_js
node_js: lts/*
cache: npm

script: echo "npm test temporarily disabled"

before_deploy:
  - npm run build:prod

deploy:
  - provider: s3
    access_key_id: AKIA43SPPSQCK65MBLJV
    secret_access_key: ${S3_KEY}
    bucket: mjclyde.com
    skip_cleanup: true
    acl: public_read
    local_dir: dist
    cache_control: "max-age=0"
    on:
      branch: master
